import type { Choice, Hardware, NodeId, OS, Story, StoryNode } from './types';
import type { UseCase } from './types';
import {
  enumerateContexts,
  hardwareFor,
  operatingSystems,
  ramOptionsFor,
  selectableHardwareFor,
  toolsFor,
  useCases,
  type PathContext,
  type ToolDef,
  type UseCaseDef,
} from './catalog';
import type { OSDef } from './catalog';
import { EXPLORE_TARGET } from './catalog/types';
import { ctxKey } from './catalog/tools/shared';
import { fixedNodes } from './fixed';

/** The use-case-selection node id; also the target of "explore another path". */
export const CHOOSE_USECASE_ID: NodeId = 'choose-usecase';

const chooseOsId = (useCase: UseCase): NodeId => `choose-os-${useCase}`;
const chooseHwId = (useCase: UseCase, os: string): NodeId =>
  `choose-hw-${useCase}-${os}`;
const chooseRamId = (useCase: UseCase, os: string, hw: Hardware): NodeId =>
  `choose-ram-${useCase}-${os}-${hw}`;
const chooseToolId = (ctx: PathContext): NodeId => `choose-tool-${ctxKey(ctx)}`;
const installId = (tool: ToolDef, ctx: PathContext): NodeId =>
  `${tool.id}-${ctxKey(ctx)}-install`;
const stepId = (tool: ToolDef, slug: string): NodeId => `${tool.id}-${slug}`;

/** Does this use case lead to at least one selectable context? */
function useCaseIsReachable(useCase: UseCaseDef): boolean {
  return operatingSystems.some((os) => osIsReachable(useCase.id, os));
}

/** Does choosing this OS (for a use case) lead anywhere (a hardware or tool step)? */
function osIsReachable(useCase: UseCase, os: OSDef): boolean {
  const hwList = hardwareFor(os);
  if (hwList.length > 0) {
    return selectableHardwareFor(useCase, os).length > 0;
  }
  // No hardware step: routes directly to tool selection.
  return toolsFor({ useCase, os: os.id }).length > 0;
}

/**
 * Where an OS choice routes: hardware step if the OS has hardware profiles, or
 * straight to tool selection.
 */
function osTarget(useCase: UseCase, os: OSDef): NodeId {
  return hardwareFor(os).length > 0
    ? chooseHwId(useCase, os.id)
    : chooseToolId({ useCase, os: os.id });
}

function buildChooseUseCase(): StoryNode {
  const choices: Choice[] = useCases.filter(useCaseIsReachable).map((uc) => ({
    label: uc.label,
    hint: uc.hint,
    to: chooseOsId(uc.id),
    // Choosing a use case invalidates any downstream selections.
    sets: {
      useCase: uc.id,
      os: undefined,
      hardware: undefined,
      ramGb: undefined,
      tool: undefined,
    },
    info: { title: `${uc.label} — background`, body: uc.info },
  }));

  return {
    id: CHOOSE_USECASE_ID,
    title: 'What do you want to do?',
    body: [
      {
        type: 'paragraph',
        text: 'Local AI is good at very different jobs. Tell us what you are here for and we will show only the tools that fit — then route the rest of the adventure to your machine.',
      },
    ],
    choices,
  };
}

function buildChooseOS(useCase: UseCaseDef): StoryNode {
  const choices: Choice[] = operatingSystems
    .filter((os) => osIsReachable(useCase.id, os))
    .map((os) => ({
      label: os.label,
      hint: os.hint,
      to: osTarget(useCase.id, os),
      // Choosing an OS invalidates any downstream selections.
      sets: {
        os: os.id,
        hardware: undefined,
        ramGb: undefined,
        tool: undefined,
      },
      info: { title: `${os.label} — background`, body: os.info },
    }));

  return {
    id: chooseOsId(useCase.id),
    title: 'Which machine are you on?',
    body: [
      {
        type: 'paragraph',
        text: 'Installation differs by operating system. Pick yours and we will route the rest of the adventure accordingly.',
      },
    ],
    choices,
  };
}

function buildChooseHardware(
  useCase: UseCase,
  os: OSDef,
): StoryNode {
  const choices: Choice[] = selectableHardwareFor(useCase, os).map((hw) => {
    let to: NodeId;
    let ramGb: number | undefined;
    if (hw.askRam && hw.id !== 'nvidia-spark') {
      to = chooseRamId(useCase, os.id, hw.id);
      ramGb = undefined;
    } else {
      // Direct to tool: nvidia-spark carries its fixed 128 GB so ctxKey matches
      // the install node generated by enumerateContexts.
      to = chooseToolId({
        useCase,
        os: os.id as OS,
        hardware: hw.id,
        ramGb: hw.id === 'nvidia-spark' ? 128 : undefined,
      });
      ramGb = hw.id === 'nvidia-spark' ? 128 : undefined;
    }
    return {
      label: hw.label,
      hint: hw.hint,
      to,
      sets: { hardware: hw.id, ramGb, tool: undefined },
      info: { title: `${hw.label} — background`, body: hw.info },
    };
  });

  return {
    id: chooseHwId(useCase, os.id),
    title: `What are you running on? (${os.label})`,
    body: [
      {
        type: 'paragraph',
        text: 'Your hardware decides which acceleration to set up and which tools make sense. Pick the closest match.',
      },
    ],
    choices,
  };
}

/**
 * Build the RAM-selection step for hardware that asks for it
 * (apple-silicon, amd-strix, cpu — but NOT nvidia-spark, which is always 128 GB).
 */
function buildChooseRam(
  useCase: UseCase,
  os: string,
  hw: Hardware,
  hwLabel: string,
): StoryNode {
  const options = ramOptionsFor(hw);
  const choices: Choice[] = options.map((tier: (typeof options)[0]) => ({
    label: tier.label,
    hint: tier.hint,
    to: chooseToolId({ useCase, os: os as OS, hardware: hw, ramGb: tier.id }),
    sets: { ramGb: tier.id, tool: undefined },
    info: { title: `${tier.label} — background`, body: tier.info },
  }));

  return {
    id: chooseRamId(useCase, os, hw),
    title: `How much RAM do you have? (${hwLabel})`,
    body: [
      {
        type: 'paragraph',
        text: 'Your RAM determines how large a model can fit comfortably. Pick your total installed RAM — this tunes the tool recommendations and setup guide to what actually works for you.',
      },
    ],
    choices,
  };
}

function buildChooseTool(ctx: PathContext): StoryNode {
  const supported = toolsFor(ctx);
  const choices: Choice[] = supported.map((tool) => ({
    label: tool.label,
    hint: tool.summary,
    to: installId(tool, ctx),
    sets: { tool: tool.id },
    info: { title: `${tool.label} — background`, body: tool.info },
  }));

  return {
    id: chooseToolId(ctx),
    title: 'Pick your tool',
    body: [
      {
        type: 'paragraph',
        text: 'These are the tools that fit your setup. Unsure? The first option is usually the smoothest place to start.',
      },
    ],
    choices,
  };
}

function buildInstallNode(tool: ToolDef, ctx: PathContext): StoryNode {
  const { title, body } = tool.install(ctx);
  const firstStep = tool.steps[0];
  return {
    id: installId(tool, ctx),
    title,
    body,
    next: firstStep ? stepId(tool, firstStep.slug) : undefined,
    terminal: firstStep ? undefined : true,
  };
}

/** Build a tool's shared follow-up step nodes (generated once per tool). */
function buildToolSteps(tool: ToolDef): StoryNode[] {
  return tool.steps.map((step) => {
    const choices: Choice[] | undefined = step.choices?.map((c) => ({
      label: c.label,
      hint: c.hint,
      to: c.to === EXPLORE_TARGET ? CHOOSE_USECASE_ID : stepId(tool, c.to),
      // "Explore another path" returns to the top of the funnel; clear all
      // downstream facts so the recap/breadcrumb reflect a fresh start.
      sets:
        c.to === EXPLORE_TARGET
          ? {
              useCase: undefined,
              os: undefined,
              hardware: undefined,
              ramGb: undefined,
              tool: undefined,
            }
          : undefined,
    }));

    return {
      id: stepId(tool, step.slug),
      title: step.title,
      body: step.body,
      next: step.nextSlug ? stepId(tool, step.nextSlug) : undefined,
      nextLabel: step.nextLabel,
      choices,
      terminal: step.terminal,
    };
  });
}

/**
 * Assembles the full story graph from the catalog. The result is a plain
 * StoryNode map — identical in shape to the hand-written graph the engine and
 * validator already understand.
 */
export function buildStory(): Story {
  const story: Story = { ...fixedNodes };

  const add = (node: StoryNode) => {
    story[node.id] = node;
  };

  add(buildChooseUseCase());

  // OS-selection steps, one per reachable use case.
  for (const useCase of useCases) {
    if (useCaseIsReachable(useCase)) add(buildChooseOS(useCase));
  }

  // Hardware-selection steps (per use case, per OS).
  for (const useCase of useCases) {
    for (const os of operatingSystems) {
      if (selectableHardwareFor(useCase.id, os).length > 0) {
        add(buildChooseHardware(useCase.id, os));
      }
    }
  }

  // RAM-selection steps (per use case, per OS, per askRam hardware — except nvidia-spark
  // which is always 128 GB and skips this step).
  for (const useCase of useCases) {
    for (const os of operatingSystems) {
      for (const hw of selectableHardwareFor(useCase.id, os)) {
        if (hw.askRam && hw.id !== 'nvidia-spark') {
          add(buildChooseRam(useCase.id, os.id, hw.id, hw.label));
        }
      }
    }
  }

  // Tool-selection steps, one per selectable context.
  for (const ctx of enumerateContexts()) {
    add(buildChooseTool(ctx));
  }

  // Install nodes, one per (tool, context).
  for (const ctx of enumerateContexts()) {
    for (const tool of toolsFor(ctx)) {
      add(buildInstallNode(tool, ctx));
    }
  }

  // Shared follow-up steps, generated once per tool.
  const seenTools = new Set<string>();
  for (const ctx of enumerateContexts()) {
    for (const tool of toolsFor(ctx)) {
      if (seenTools.has(tool.id)) continue;
      seenTools.add(tool.id);
      for (const node of buildToolSteps(tool)) add(node);
    }
  }

  return story;
}